source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!
platform :ios, '11.0'

target 'YoutubePlayerView_Example' do
  pod 'YoutubePlayerView', :path => '../'

  target 'YoutubePlayerView_Tests' do
    inherit! :search_paths

    
  end
end
